"""init schema

Revision ID: 11e5f877d31f
Revises: c3f1b2d4e5f6
Create Date: 2026-03-11 14:54:31.403835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '11e5f877d31f'
down_revision: Union[str, Sequence[str], None] = 'c3f1b2d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_presets_id'), table_name='presets')
    op.drop_index(op.f('ix_presets_name'), table_name='presets')
    op.drop_table('presets')
    op.drop_table('layers')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('filepath', sa.VARCHAR(), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('format', sa.VARCHAR(length=50), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('z_index', sa.INTEGER(), nullable=True),
    sa.Column('locked', sa.BOOLEAN(), nullable=True),
    sa.Column('opacity', sa.INTEGER(), nullable=True),
    sa.Column('visible', sa.BOOLEAN(), nullable=True),
    sa.Column('x', sa.FLOAT(), nullable=True),
    sa.Column('y', sa.FLOAT(), nullable=True),
    sa.Column('width', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('blend_mode', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('exposure', sa.FLOAT(), nullable=True),
    sa.Column('brightness', sa.FLOAT(), nullable=True),
    sa.Column('contrast', sa.FLOAT(), nullable=True),
    sa.Column('highlights', sa.FLOAT(), nullable=True),
    sa.Column('shadows', sa.FLOAT(), nullable=True),
    sa.Column('saturation', sa.FLOAT(), nullable=True),
    sa.Column('sharpness', sa.FLOAT(), nullable=True),
    sa.Column('custom_params', sqlite.JSON(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_name'), 'presets', ['name'], unique=False)
    op.create_index(op.f('ix_presets_id'), 'presets', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('cover_image', sa.VARCHAR(), nullable=True),
    sa.Column('cover_original_width', sa.INTEGER(), nullable=True),
    sa.Column('cover_original_height', sa.INTEGER(), nullable=True),
    sa.Column('cover_crop_x', sa.INTEGER(), nullable=True),
    sa.Column('cover_crop_y', sa.INTEGER(), nullable=True),
    sa.Column('cover_crop_width', sa.INTEGER(), nullable=True),
    sa.Column('cover_crop_height', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###